server:
  port: 8080

spring:
    datasource:
        url: jdbc:mysql://192.168.191.157:3306/shopping?characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: test
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml     #mapper文件路径
  type-aliases-package: com.example.adminmanager.pojo  #实体类的包路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
